func handleRequest(w http.ResponseWriter, r *http.Request) {
    // ... other code ...
    if r.Method == "POST" {
        // ... other code ...
        defer r.Body.Close()
        // ... process request body ...
    }
}